<?php
/**
 * Copy this file to contact-config.php (same folder) and fill in the values.
 *
 * contact-config.php is gitignored — credentials must never be committed.
 * Because it is a .php file, requesting it directly returns nothing: PHP
 * executes it and the returned array is never printed.
 *
 * On deploys this file is generated by GitHub Actions from repository secrets,
 * so edits made on the server are overwritten by the next deploy.
 */

return [
  // How the mail is sent:
  //   'smtp'   - authenticate to a mail server and send. Works even when the
  //              host disables mail(), which most shared hosts now do.
  //   'php'    - hand it to the local mail server via mail().
  //   'resend' - call the Resend HTTP API. Requires a verified domain.
  // Leave empty to auto-pick: resend if a key is set, else smtp if a host is
  // set, else php.
  'MAIL_TRANSPORT' => 'smtp',

  // --- SMTP settings (MAIL_TRANSPORT = 'smtp') ---
  // On cPanel this is usually mail.<yourdomain> on port 465 with SSL.
  // Port 587 with SMTP_SECURE = 'tls' also works on most hosts.
  'SMTP_HOST' => 'mail.orbitwelve.com',
  'SMTP_PORT' => '465',
  'SMTP_SECURE' => 'ssl', // 'ssl' | 'tls' | 'none'
  'SMTP_USER' => 'contact@orbitwelve.com',
  'SMTP_PASS' => '',      // the mailbox password from cPanel > Email Accounts

  // Only used when MAIL_TRANSPORT is 'resend'.
  'RESEND_API_KEY' => '',

  // The sender address. Must be a real mailbox on your own domain — for SMTP
  // it normally has to match SMTP_USER, or the server rejects the message.
  'CONTACT_EMAIL_FROM' => 'Orbitwelve Website <contact@orbitwelve.com>',

  // Where submissions land. Comma-separate for multiple recipients.
  'CONTACT_EMAIL_TO' => 'contact@orbitwelve.com',

  // Browser origins allowed to POST to this endpoint.
  'ALLOWED_ORIGINS' => [
    'https://orbitwelve.com',
    'https://www.orbitwelve.com',
    'http://localhost:3000',
  ],
];
